import { ArrowLeft, CheckCircle2, Mail, ShieldCheck } from "lucide-react";
import { Link, useLocation } from "wouter";
import { Button } from "@/components/ui/button";
import PublicShell from "@/components/PublicShell";

const content = {
  "/about": { eyebrow: "SENSE / ABOUT", title: "مدن أسهل، وتجارب أكثر إنصافًا", intro: "SENSE منصة رقمية تربط الوصول الحضري بالسياحة الشاملة والخدمات البلدية والمنتجات المهيأة، مع إبقاء البيانات الواضحة والقرار الإنساني في مركز التجربة.", sections: [{ title: "ماذا نبني؟", text: "نبني طبقة رقمية تساعد السكان والزوار والجهات المحلية على فهم خصائص الوصول قبل اتخاذ القرار، ثم تحويل الملاحظات إلى تحسينات قابلة للمتابعة." }, { title: "مبدأ التحقق", text: "لا نعتبر معلومة الوصول حقيقة نهائية دون مصدر أو تحقق ميداني وتاريخ مراجعة واضح. كما لا نستخدم مراجعات أو شهادات عملاء مصطنعة." }] },
  "/help": { eyebrow: "SENSE / HELP", title: "ابدأ بخطوة واضحة", intro: "إذا كنت زائرًا أو مواطنًا أو مزود خدمة، ستجد هنا مسارات مختصرة للوصول إلى الجزء المناسب من المنصة.", sections: [{ title: "للتخطيط", text: "احفظ تفضيلات الوصول من صفحة تجربتك، ثم استخدم مخطط الرحلة لبناء قائمة أولية قابلة للتعديل." }, { title: "للبلاغات", text: "استخدم مسار البلاغ عندما يصبح متاحًا في نسخته التشغيلية. لا تُرسل بيانات حساسة أو صور أشخاص دون موافقة واضحة." }, { title: "للمساعدة", text: "إذا وجدت معلومة وصول غير دقيقة، احتفظ باسم الوجهة ومصدر المعلومة وتاريخ الملاحظة عند التواصل معنا." }] },
  "/privacy": { eyebrow: "SENSE / PRIVACY", title: "خصوصيتك جزء من الوصول", intro: "هذه صفحة تعريفية أولية وليست بديلًا عن مراجعة قانونية نهائية قبل تشغيل جمع البيانات على نطاق واسع.", sections: [{ title: "ما نحفظه الآن", text: "إعدادات تجربة الوصول الحالية تُحفظ محليًا على جهازك. لا تُرسل هذه التفضيلات إلى الخادم ضمن النسخة الحالية ما لم يذكر المسار ذلك صراحة." }, { title: "ما سنبنيه قبل التشغيل", text: "سيحتاج نظام البلاغات إلى سياسة احتفاظ وحذف وتصنيف بيانات وسجل وصول واضح، ولن نعتبره جاهزًا قبل توثيقها واختبار صلاحياتها." }] },
  "/terms": { eyebrow: "SENSE / TERMS", title: "استخدام مسؤول وواضح", intro: "تساعد SENSE على الفهم والتخطيط، لكنها لا تستبدل التحقق الميداني أو القرار البلدي أو الاستشارة المتخصصة.", sections: [{ title: "المعلومات الإرشادية", text: "أي وصف للوصول أو المسارات المقترحة يحتاج إلى مراجعة المستخدم قبل الزيارة، خصوصًا عند تغير الطقس أو أعمال الطرق أو حالة المرفق." }, { title: "المحتوى والحقوق", text: "لا ترفع صورًا أو مستندات لا تملك حق استخدامها. عند تشغيل البلاغات، ستُعرض الموافقات والاحتفاظ والاستخدام قبل الإرسال." }] },
  "/contact": { eyebrow: "SENSE / CONTACT", title: "لنبنِ خدمة أوضح معًا", intro: "نستقبل ملاحظات الجهات المحلية ومزودي الخدمات والزوار حول الوصول الحضري والسياحة الشاملة.", sections: [{ title: "التواصل", text: "للمراجعة الأولية، أرسل اسم الجهة أو الوجهة، وصف الملاحظة، تاريخها، ومصدر التحقق إن توفر. لا ترسل بيانات شخصية غير لازمة." }] },
} as const;

export default function InfoPage() {
  const [location] = useLocation();
  const page = content[location as keyof typeof content] ?? content["/help"];
  return <PublicShell><main className="min-h-screen bg-[#f7faff]"><section className="sense-grid text-white"><div className="container py-20"><div className="eyebrow text-[#f5c542]">{page.eyebrow}</div><h1 className="mt-5 max-w-3xl text-5xl font-black leading-tight md:text-7xl">{page.title}</h1><p className="mt-6 max-w-2xl text-lg leading-9 text-blue-100/80">{page.intro}</p></div></section><section className="container py-16"><div className="grid gap-5 md:grid-cols-2">{page.sections.map((section) => <article key={section.title} className="cad-frame bg-white p-7"><div className="flex items-center gap-3 text-[#1355a3]"><CheckCircle2 size={20} /><h2 className="text-xl font-black text-[#071b42]">{section.title}</h2></div><p className="mt-4 leading-8 text-[#647b96]">{section.text}</p></article>)}</div><div className="mt-10 flex flex-wrap gap-3"><Link href="/help"><Button className="bg-[#1355a3] text-white hover:bg-[#0e4387]">مركز المساعدة <ArrowLeft size={17} /></Button></Link><Link href="/contact"><Button variant="outline" className="border-[#b4c9e0] bg-white text-[#071b42]"><Mail size={16} /> تواصل معنا</Button></Link><Link href="/preferences"><Button variant="outline" className="border-[#b4c9e0] bg-white text-[#071b42]"><ShieldCheck size={16} /> تخصيص التجربة</Button></Link></div></section></main></PublicShell>;
}
