import { ArrowLeft, BadgeCheck, Gift, PackageCheck, Search, ShoppingBag, Store, Tag } from "lucide-react";
import { Link } from "wouter";
import { Button } from "@/components/ui/button";
import PublicShell from "@/components/PublicShell";

const collections = [
  { title: "أدوات رحلة أيسر", detail: "منتجات مساندة للسفر والتنقل والراحة.", icon: PackageCheck },
  { title: "صناعة محلية أصيلة", detail: "منتجات من صناع ومشاريع محلية يمكن التعرف عليهم.", icon: Gift },
  { title: "حزم التجربة", detail: "اختيارات تجمع منتجًا وخدمة لتسهيل التخطيط.", icon: Tag },
];

export default function LocalMarket() {
  return <PublicShell><main className="bg-[#f7faff]"><section className="sense-grid py-20 text-white"><div className="container grid gap-10 lg:grid-cols-[1fr_.8fr] lg:items-end"><div><div className="eyebrow text-[#f5c542]">SENSE / LOCAL MARKET</div><h1 className="mt-5 max-w-3xl text-5xl font-black leading-tight md:text-6xl">السوق المحلي<br /><span className="text-[#f5c542]">جزء من رحلتك.</span></h1><p className="mt-6 max-w-2xl text-lg leading-8 text-blue-100/80">منتجات محلية وخيارات مساندة تساعدك على الاستعداد، وتصل إليك من مزودين نعرف قصتهم ونوضح خصائص منتجاتهم.</p></div><div className="bg-white p-2 text-[#071b42]"><div className="flex items-center gap-3 px-3"><Search className="text-[#1355a3]" size={20} /><input aria-label="ابحث في السوق" placeholder="ابحث عن منتج أو حزمة" className="min-w-0 flex-1 bg-transparent py-4 outline-none" /><Button className="bg-[#f5c542] text-[#071b42] hover:bg-[#ffd967]">بحث</Button></div></div></div></section><section className="container py-16"><div className="flex items-end justify-between gap-4"><div><div className="eyebrow text-[#1355a3]">CURATED COLLECTIONS</div><h2 className="mt-3 text-3xl font-black text-[#071b42]">اختيارات تبدأ من احتياجك</h2></div><Link href="/shop"><Button variant="outline" className="border-[#b4c9e0] bg-white text-[#071b42]"><ShoppingBag size={17} /> تصفح المتجر</Button></Link></div><div className="mt-10 grid gap-5 md:grid-cols-3">{collections.map(({ title, detail, icon: Icon }) => <article key={title} className="cad-frame bg-white p-7 sense-shadow"><div className="flex items-center justify-between"><div className="grid h-12 w-12 place-items-center bg-[#e8f1fc] text-[#1355a3]"><Icon /></div><BadgeCheck className="text-[#159a77]" size={20} /></div><h3 className="mt-10 text-xl font-black text-[#071b42]">{title}</h3><p className="mt-3 leading-7 text-[#647b96]">{detail}</p><Link href="/shop" className="mt-7 inline-flex items-center gap-2 text-sm font-black text-[#1355a3]">استكشف الاختيارات <ArrowLeft size={15} /></Link></article>)}</div></section><section className="container pb-20"><div className="grid gap-5 md:grid-cols-3"><div className="bg-[#071b42] p-7 text-white"><Store className="text-[#f5c542]" /><h3 className="mt-7 text-xl font-black">للمزودين المحليين</h3><p className="mt-3 text-sm leading-7 text-blue-100/70">اعرض منتجك ومعلوماته بوضوح، وكن جزءًا من رحلة أكثر شمولًا.</p><Button className="mt-6 bg-[#f5c542] text-[#071b42] hover:bg-[#ffd967]">انضم كمزود</Button></div><div className="border border-[#dce7f3] bg-white p-7 md:col-span-2"><h3 className="text-xl font-black text-[#071b42]">لا نعرض مراجعات أو شهادات مصطنعة</h3><p className="mt-3 max-w-2xl leading-7 text-[#647b96]">نوضح مصدر كل معلومة، ونفصل بين خصائص المنتج وتجربة المستخدم. التقييم لا يظهر إلا بعد عملية حقيقية، وبمشاركة فعلية من صاحبه.</p></div></div></section></main></PublicShell>;
}
