import DashboardLayout from "@/components/DashboardLayout";
import { trpc } from "@/lib/trpc";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { ShoppingBag, ArrowLeft } from "lucide-react";
import { Link } from "wouter";

const statusLabels: Record<string, string> = { pending_payment: "بانتظار الدفع", paid: "تم الدفع", processing: "قيد التجهيز", shipped: "تم الشحن", delivered: "تم التسليم", cancelled: "ملغى", refunded: "مُسترد", requires_review: "يحتاج مراجعة" };

export default function Orders() {
  const query = trpc.commerce.checkout.mine.useQuery();
  return <DashboardLayout><main dir="rtl" className="min-h-[calc(100vh-2rem)] bg-[#eef4fb] p-4 md:p-8"><div className="mx-auto max-w-5xl"><p className="text-xs font-black tracking-[.2em] text-[#1355a3]">SENSE / ORDERS</p><h1 className="mt-2 text-3xl font-black text-[#071b42]">طلباتي داخل SENSE</h1><p className="mt-3 max-w-3xl text-[#647b96]">هذا السجل يعتمد على قاعدة SENSE الداخلية. تتولى موصلات الدفع والشحن الخارجية معالجة مراحلها دون تخزين بيانات البطاقة داخل المنصة.</p>{query.isLoading && <p className="mt-8">جارٍ تحميل الطلبات…</p>}{query.isError && <p className="mt-8 rounded border border-red-200 bg-red-50 p-4 text-red-800">تعذر تحميل الطلبات الآن.</p>}{!query.isLoading && !query.isError && (!query.data || query.data.length === 0) && <Card className="mt-8 border-dashed shadow-none"><CardContent className="flex flex-col items-center gap-3 p-12 text-center"><ShoppingBag className="size-10 text-[#1355a3]" /><p className="font-bold">لا توجد طلبات بعد</p><p className="text-sm text-[#647b96]">تصفح المتجر وأضف المنتجات المعتمدة إلى سلتك.</p></CardContent></Card>}{query.data && query.data.length > 0 && <div className="mt-8 grid gap-4">{query.data.map(order => <Card key={order.id} className="border-[#cbdced] shadow-none"><CardHeader><CardTitle className="flex items-center justify-between gap-4 text-base"><span>طلب {order.orderNumber}</span><span className="rounded bg-[#fff3bf] px-3 py-1 text-xs">{statusLabels[order.status] ?? order.status}</span></CardTitle></CardHeader><CardContent className="flex flex-wrap items-center justify-between gap-4"><span className="text-sm text-[#647b96]">{new Date(order.createdAt).toLocaleString("ar-SA")}</span><Link href={`/orders/${order.id}`} className="inline-flex items-center gap-2 font-bold text-[#1355a3]">التفاصيل <ArrowLeft className="size-4" /></Link></CardContent></Card>)}</div>}</div></main></DashboardLayout>;
}
