import DashboardLayout from "@/components/DashboardLayout";
import { trpc } from "@/lib/trpc";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { ExternalLink, ShoppingBag } from "lucide-react";

export default function Orders() {
  const { data, isLoading, isError } = trpc.commerce.checkout.mine.useQuery();
  return <DashboardLayout><main dir="rtl" className="min-h-[calc(100vh-2rem)] bg-[#eef4fb] p-4 md:p-8"><div className="mx-auto max-w-5xl"><p className="text-xs font-black tracking-[.2em] text-[#1355a3]">SENSE / ORDERS</p><h1 className="mt-2 text-3xl font-black text-[#071b42]">سجل إحالات الشراء</h1><p className="mt-3 max-w-3xl text-[#647b96]">يظهر هنا ما تم تحويله إلى Checkout الخارجي من حسابك. لا نعرض حالة الدفع أو الشحن من داخل SENSE قبل توفر مصدر موثوق من Shopify.</p>{isLoading && <p className="mt-8">جارٍ تحميل السجل…</p>}{isError && <p className="mt-8 rounded border border-red-200 bg-red-50 p-4 text-red-800">تعذر تحميل السجل الآن.</p>}{!isLoading && !isError && (!data || data.length === 0) && <Card className="mt-8 border-dashed shadow-none"><CardContent className="flex flex-col items-center gap-3 p-12 text-center"><ShoppingBag className="size-10 text-[#1355a3]" /><p className="font-bold">لا توجد إحالات شراء محفوظة</p><p className="text-sm text-[#647b96]">يمكنك تصفح المتجر والمتابعة كضيف أو بعد تسجيل الدخول.</p></CardContent></Card>}{data && data.length > 0 && <div className="mt-8 grid gap-4">{data.map((handoff) => <Card key={handoff.id} className="border-[#cbdced] shadow-none"><CardHeader><CardTitle className="flex items-center justify-between gap-4 text-base"><span>إحالة Checkout #{handoff.id}</span><span className="rounded bg-[#fff3bf] px-3 py-1 text-xs">محال إلى المتجر</span></CardTitle></CardHeader><CardContent className="flex flex-wrap items-center justify-between gap-4"><time className="text-sm text-[#647b96]">{new Date(handoff.createdAt).toLocaleString("ar-SA")}</time><a href={handoff.checkoutUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 font-bold text-[#1355a3]">فتح Checkout <ExternalLink className="size-4" /></a></CardContent></Card>)}</div>}</div></main></DashboardLayout>;
}
