import { Link, useParams } from "wouter";
import { ArrowRight, ShoppingBag } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import DashboardLayout from "@/components/DashboardLayout";
import { trpc } from "@/lib/trpc";
import { parseOrderId } from "./orderDetailState";

export default function OrderDetail() {
  const params = useParams<{ id: string }>();
  const id = parseOrderId(params.id);
  const validId = id !== null;
  const query = trpc.commerce.checkout.byId.useQuery({ id: id ?? 0 }, { enabled: validId });
  return <DashboardLayout><main dir="rtl" className="min-h-[calc(100vh-2rem)] bg-[#eef4fb] p-4 md:p-8"><div className="mx-auto max-w-3xl"><Link href="/orders" className="inline-flex items-center gap-2 text-sm font-bold text-[#1355a3]"><ArrowRight className="size-4" /> العودة إلى طلباتي</Link><p className="mt-8 text-xs font-black tracking-[.2em] text-[#1355a3]">SENSE / ORDER DETAIL</p><h1 className="mt-2 text-3xl font-black text-[#071b42]">تفاصيل الطلب</h1><p className="mt-3 text-[#647b96]">هذا الطلب محفوظ داخل SENSE، وسيُحدّث الدفع والشحن عبر موصلات الشركاء بعد تفعيلها.</p>{!validId && <Card className="mt-8 border-red-200 shadow-none"><CardContent className="p-8 text-center text-red-800">رقم الطلب غير صالح.</CardContent></Card>}{validId && query.isLoading && <p className="mt-8">جارٍ تحميل تفاصيل الطلب…</p>}{validId && query.isError && <Card className="mt-8 border-red-200 bg-red-50 shadow-none"><CardContent className="p-8 text-center text-red-800">تعذر تحميل تفاصيل الطلب الآن.</CardContent></Card>}{validId && !query.isLoading && !query.isError && !query.data && <Card className="mt-8 border-dashed shadow-none"><CardContent className="flex flex-col items-center gap-3 p-12 text-center"><ShoppingBag className="size-10 text-[#1355a3]" /><p className="font-bold">لم نعثر على هذا الطلب</p><p className="text-sm text-[#647b96]">قد يكون الطلب غير تابع لحسابك.</p></CardContent></Card>}{query.data && <Card className="mt-8 border-[#cbdced] shadow-none"><CardHeader><CardTitle className="flex items-center justify-between gap-4 text-base"><span>{query.data.orderNumber}</span><span className="rounded bg-[#fff3bf] px-3 py-1 text-xs">{query.data.status}</span></CardTitle></CardHeader><CardContent className="space-y-6"><dl className="grid gap-4 sm:grid-cols-2"><div><dt className="text-sm text-[#647b96]">الإجمالي</dt><dd className="mt-1 font-bold">{((query.data.totalMinor ?? 0) / 100).toFixed(2)} {query.data.currency}</dd></div><div><dt className="text-sm text-[#647b96]">تاريخ الإنشاء</dt><dd className="mt-1 font-bold">{new Date(query.data.createdAt).toLocaleString("ar-SA")}</dd></div><div><dt className="text-sm text-[#647b96]">حالة الدفع</dt><dd className="mt-1 font-bold">{query.data.paymentStatus}</dd></div><div><dt className="text-sm text-[#647b96]">حالة الشحن</dt><dd className="mt-1 font-bold">{query.data.fulfillmentStatus}</dd></div></dl><div className="rounded border border-[#cbdced] bg-[#f8fbff] p-4 text-sm leading-7 text-[#38516d]">لم تُخزّن بيانات البطاقة في SENSE. سيُضاف رابط الدفع ورقم التتبع فقط من خلال موصل الشريك بعد تفعيل التوقيع وسجل التدقيق.</div></CardContent></Card>}</div></main></DashboardLayout>;
}
