import { ArrowRight, BadgeCheck, MapPinned, Package, ShieldCheck } from "lucide-react";
import { Link, useLocation } from "wouter";
import PublicShell from "@/components/PublicShell";
import { trpc } from "@/lib/trpc";

export default function ProviderDetail() {
  const [location] = useLocation();
  const parts = location.split("/").filter(Boolean);
  const kind = parts[1] === "service" ? "service" : "product";
  const id = Number(parts[2]);
  const catalog = trpc.providers.publicCatalog.useQuery();
  const item = kind === "service" ? catalog.data?.services.find((entry) => entry.id === id) : catalog.data?.products.find((entry) => entry.id === id);

  return <PublicShell><main dir="rtl" className="min-h-[70vh] bg-[#f7faff] py-16"><div className="container max-w-5xl"><Link href="/providers" className="inline-flex items-center gap-2 text-sm font-black text-[#1355a3]"><ArrowRight size={16} /> العودة إلى دليل المزودين</Link>{catalog.isLoading ? <div className="cad-frame mt-8 bg-white p-10 text-[#647b96]">جارٍ تحميل التفاصيل...</div> : !item ? <div className="cad-frame mt-8 bg-white p-10"><h1 className="text-3xl font-black text-[#071b42]">العنصر غير متاح</h1><p className="mt-3 leading-7 text-[#647b96]">لا يظهر هنا إلا المحتوى المنشور من مزود معتمد. قد يكون العنصر غير منشور أو تم أرشفته.</p></div> : <article className="mt-8 grid gap-8 lg:grid-cols-[.72fr_1.28fr]"><div className="sense-grid-fine cad-frame grid min-h-[280px] place-items-center bg-[#e8f1fc] text-[#1355a3]">{kind === "service" ? <MapPinned size={74} strokeWidth={1.1} /> : "imageUrl" in item && item.imageUrl ? <img src={item.imageUrl} alt={item.name} className="h-full max-h-[360px] w-full object-contain" /> : <Package size={74} strokeWidth={1.1} />}</div><div className="cad-frame bg-white p-8"><div className="flex items-center justify-between gap-4"><span className="text-sm font-black text-[#1355a3]">{kind === "service" ? "خدمة من مزود معتمد" : "منتج من مزود معتمد"}</span><BadgeCheck className="text-[#159a77]" size={22} /></div><h1 className="mt-5 text-4xl font-black text-[#071b42]">{item.name}</h1>{item.description && <p className="mt-5 whitespace-pre-line leading-8 text-[#647b96]">{item.description}</p>}<div className="mt-8 grid gap-3 border-t border-[#e6eef7] pt-6 text-sm text-[#071b42]"><div className="flex items-start gap-3"><ShieldCheck className="mt-0.5 text-[#159a77]" size={18} /><span>المعلومة منشورة بعد اعتماد ملف المزود، وتبقى التفاصيل التشغيلية قابلة للتحديث.</span></div>{kind === "service" && "accessibilityNotes" in item && item.accessibilityNotes && <div className="flex items-start gap-3"><MapPinned className="mt-0.5 text-[#1355a3]" size={18} /><span><strong>ملاحظات الوصول:</strong> {item.accessibilityNotes}</span></div>}{kind === "service" && "serviceArea" in item && item.serviceArea && <div><strong>نطاق الخدمة:</strong> {item.serviceArea}</div>}{"priceMinor" in item && item.priceMinor !== null && <div><strong>السعر المعلن:</strong> {(item.priceMinor / 100).toFixed(2)} {item.currency}</div>}</div><div className="mt-8 flex flex-wrap gap-3"><Link href={kind === "service" ? "/plan" : "/store"} className="inline-flex items-center gap-2 bg-[#f5c542] px-5 py-3 font-black text-[#071b42]">{kind === "service" ? "أضف إلى مخطط الرحلة" : "استكشف المتجر"}</Link><Link href="/contact" className="inline-flex items-center gap-2 border border-[#b4c9e0] px-5 py-3 font-black text-[#1355a3]">استفسر قبل الاختيار</Link></div></div></article>}</div></main></PublicShell>;
}
